const tasks = [
  {
    title: "Broken drawer slider",
    description: "The drawer slider is broken and needs to be replaced",
    location: "NU404 A1",
    status: "pending",
    toolsRequired: ["Screwdriver", "Hammer", "Slider replacement"],
    dateCreated: new Date(),
  },
  {
    title: "Leaky faucet",
    description: "The faucet in the kitchen is leaking and needs to be fixed",
    location: "MS201",
    status: "pending",
    toolsRequired: ["Wrench", "Sealant"],
    dateCreated: new Date(),
  },
  {
    title: "Broken chair",
    description: "The chair in the conference room is broken and needs to be fixed",
    location: "CR301",
    status: "pending",
    toolsRequired: ["Screwdriver", "Glue"],
    dateCreated: new Date(),
  },
  {
    title: "Broken light bulb",
    description: "The light bulb in the hallway is broken and needs to be replaced",
    location: "Hallway",
    status: "pending",
    toolsRequired: ["Ladder", "Light bulb"],
    dateCreated: new Date(),
  },
  {
    title: "Broken window",
    description: "The window in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Glass cutter", "Glass replacement"],
    dateCreated: new Date(),
  },
  {
    title: "Leaky roof",
    description: "The roof is leaking and needs to be fixed",
    location: "Roof",
    status: "pending",
    toolsRequired: ["Ladder", "Sealant"],
    dateCreated: new Date(),
  },
  {
    title: "Broken desk",
    description: "The desk in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Screwdriver", "Glue"],
    dateCreated: new Date(),
  },
  {
    title: "Broken door",
    description: "The door in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Screwdriver", "Glue"],
    dateCreated: new Date(),
  },
  {
    title: "Broken chair",
    description: "The chair in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Screwdriver", "Glue"],
    dateCreated: new Date(),
  },
  {
    title: "Broken table",
    description: "The table in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Screwdriver", "Glue"],
    dateCreated: new Date(),
  },
  {
    title: "Broken window",
    description: "The window in the office is broken and needs to be fixed",
    location: "Office",
    status: "pending",
    toolsRequired: ["Glass cutter", "Glass replacement"],
    dateCreated: new Date(),
  },
];

module.exports = tasks;
