FROM node:18.16.0
WORKDIR /usr/src/node_app
COPY ./package*.json /usr/src/node_app/
RUN npm install && npm install pm2 -g && npm install -g typescript ts-node
RUN pm2 install typescript
COPY ./ /usr/src/node_app/
EXPOSE 5000
CMD ["pm2-runtime", "start", "./src/server.ts"]