FROM node:18.16.0
WORKDIR /usr/src/node_app
COPY ./package*.json /usr/src/node_app/
RUN npm install && npm install pm2 -g
COPY ./ /usr/src/node_app/
EXPOSE 5000
CMD ["pm2-runtime", "start", "index.js"]